#!groovy

// Generated by IBM TransformationAdvisor
// Thu Nov 22 10:03:03 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}