#!groovy

// Generated by IBM TransformationAdvisor
// Tue Nov 13 09:23:53 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}