#!groovy

// Generated by IBM TransformationAdvisor
// Mon Nov 12 15:17:25 UTC 2018

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}